#!/bin/bash
set -e
source /etc/os-release
BASEDIR=$(dirname "$0")
mkdir -p ~/.config/nvim
rm -rf fzf
[ ! -f "fzf" ] && git clone --depth 1 https://github.com/junegunn/fzf.git fzf
[ -f "~/.config/nvim/init.vim" ] && mv ~/.config/nvim/init.vim ~/.config/nvim/init.vim.`date +%F_%R`
cp  $BASEDIR/init.vim ~/.config/nvim/.
[ -f "$BASEDIR/plugins/autoload"  ] && cp -r $BASEDIR/plugins/autoload ~/.config/nvim
[ -f "$BASEDIR/plugins/plugged" ] && cp -r $BASEDIR/plugins/plugged ~/.config/nvim

if [ $ID = 'ubuntu' ]; then
    [ ! -f "$BASEDIR/plugins" ] && mkdir -p ~/.config/nvim/autoload/plug.vim && wget https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
if [ $ID = 'centos' ] || [ $ID = 'rhel' ];then
    [ ! -f "$BASEDIR/plugins" ] && curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

cp -r $BASEDIR/fzf ~/.fzf
~/.fzf/install --all
nvim +PlugInstall +qa
